
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 20 08:50:10 KST 2013
//----------------------------------------------------

package pe.sccu.algebra.parser;

/** CUP generated interface containing symbol constants. */
public interface AlgebraSym {
  /* terminals */
  public static final int NUM = 2;
  public static final int EOF = 0;
  public static final int PLUS = 5;
  public static final int VAR = 3;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int MUL = 6;
  public static final int LPAREN = 7;
  public static final int EXP = 4;
}

